# Generated by Django 2.2.3 on 2019-08-02 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField(help_text='YYYY-MM-DD', verbose_name='Exam Date')),
                ('exam_time', models.TimeField(verbose_name='Exam time')),
                ('max_marks', models.IntegerField(verbose_name='Maximum Marks')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.Subject')),
            ],
        ),
    ]
