# Generated by Django 2.2.3 on 2019-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0005_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(),
        ),
    ]
