# Generated by Django 2.2.3 on 2019-08-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0009_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
