# Generated by Django 2.2.3 on 2019-07-31 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, help_text='yy-mm-dd')),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, help_text='yy-mm-dd')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.Department')),
                ('subject_id', models.ManyToManyField(through='users.Teacher_Subject', to='school_data.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TeacherProfile'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField()),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.Department')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='users.ParentProfile')),
                ('subject_id', models.ManyToManyField(through='users.Student_Subject', to='school_data.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student_subject',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StudentProfile'),
        ),
        migrations.AddField(
            model_name='student_subject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='student_subject',
            unique_together={('student_id', 'subject_id')},
        ),
    ]
