# Generated by Django 2.2.3 on 2019-08-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0010_delete_exam'),
        ('users', '0002_auto_20190731_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('max_marks', models.IntegerField(verbose_name='Maximum Marks')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.Subject')),
            ],
            options={
                'unique_together': {('subject_id', 'exam_date')},
            },
        ),
    ]
