# Generated by Django 2.2.3 on 2019-08-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
