# Generated by Django 2.2.3 on 2019-08-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0010_delete_exam'),
        ('users', '0005_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lecture', models.DateField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.Subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TeacherProfile')),
            ],
            options={
                'unique_together': {('subject_id', 'teacher_id', 'date_of_lecture')},
            },
        ),
    ]
