# Generated by Django 2.2.3 on 2019-08-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'get_latest_by': '-date_of_lecture'},
        ),
    ]
