# Generated by Django 2.2.3 on 2019-08-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190804_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Attendance',
        ),
    ]
